name: Deploy Laravel to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Laravel
        run: |
          cd $GITHUB_WORKSPACE
          composer install
          cp .env.example .env
          echo "APP_ENV=production" >> .env
          php artisan key:generate

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install Node.js dependencies
        run: |
          cd $GITHUB_WORKSPACE
          npm install --production

      - name: Build JavaScript
        run: |
          cd $GITHUB_WORKSPACE
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $GITHUB_WORKSPACE/laravel/public
