name: Deploy Laravel to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Laravel
        run: |
          
          composer install
          cp .env.example .env
          echo "APP_ENV=production" >> .env
          php artisan key:generate

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Build JavaScript
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./laravel/public
