name: Deploy Laravel to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ./
            destination: ./_site
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Laravel
        run: |
          cd ./laravel
          composer install
          cp .env.example .env
          echo "APP_ENV=production" >> .env
          php artisan key:generate

      - name: Install Node.js dependencies
        run: |
          cd ./laravel
          npm install

      - name: Build JavaScript
        run: |
          cd ./laravel
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./laravel/public
